CMT_tag=$(tag)
CMTROOT=/home/lucas/GlastExternals/CMT/v1r16p20040701
CMT_root=/home/lucas/GlastExternals/CMT/v1r16p20040701
CMTVERSION=v1r16p20040701
CMTrelease=15
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/lucas/Glast/ScienceTools-v7r6p1/InstallArea/rh9_gcc32/bin:${ROOTSYS}/bin:/home/lucas/GlastExternals/CMT/v1r16p20040701/${CMTBIN}:/home/lucas/headas-6.1.2/i686-pc-linux-gnu-libc2.2.4/bin:/home/lucas/bin:/home/lucas/scripts:/usr/sue/bin:/usr/local/bin:/usr/local/bin/X11:/usr/bin:/bin:/usr/bin/X11:/cern/pro/bin:/usr/kerberos/bin:/usr/X11R6/bin:/home/lucas/Glast/ScienceTools-v7r6p1/bin:/home/lucas/Glast/ScienceTools-v7r6p1/bin:/home/lucas/Glast/GlastRelease-v9r9p1/bin
CLASSPATH=/home/lucas/Glast/ScienceTools-v7r6p1/InstallArea/share/bin:/home/lucas/Glast/ScienceTools-v7r6p1/InstallArea/share/lib:/home/lucas/GlastExternals/CMT/v1r16p20040701/java
debug_option=-g
cc=gcc
cdebugflags=$(debug_option)
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppdebugflags=$(debug_option)
cppflags=-pipe -ansi -W -Wall  -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE  -I../src -DTRAP_FPE 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppoptions) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic  $(linkdebug)
cpplink=$(cpp)   $(cpplinkflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=flex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -s 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=i686-unknown00-gcc34
irfs_tag=$(tag)
IRFSROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/v0r9p2
irfs_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/v0r9p2
IRFSVERSION=v0r9p2
irfs_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
irfs_project=Project2
irfInterface_tag=$(tag)
IRFINTERFACEROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/irfInterface/v1r1
irfInterface_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/irfInterface/v1r1
IRFINTERFACEVERSION=v1r1
irfInterface_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
irfInterface_offset=irfs
irfInterface_project=Project2
GlastPolicy_tag=$(tag)
GLASTPOLICYROOT=/home/lucas/Glast/GlastRelease-v9r9p1/GlastPolicy/v6r9
GlastPolicy_root=/home/lucas/Glast/GlastRelease-v9r9p1/GlastPolicy/v6r9
GLASTPOLICYVERSION=v6r9
GlastPolicy_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
GlastPolicy_project=Project1
GlastPatternPolicy_tag=$(tag)
GLASTPATTERNPOLICYROOT=/home/lucas/Glast/GlastRelease-v9r9p1/GlastPolicy/GlastPatternPolicy/v1r3p1
GlastPatternPolicy_root=/home/lucas/Glast/GlastRelease-v9r9p1/GlastPolicy/GlastPatternPolicy/v1r3p1
GLASTPATTERNPOLICYVERSION=v1r3p1
GlastPatternPolicy_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
GlastPatternPolicy_offset=GlastPolicy
GlastPatternPolicy_project=Project1
GlastMain=${GLASTPOLICYROOT}/src/GlastMain.cxx
TestGlastMain=${GLASTPOLICYROOT}/src/TestGlastMain.cxx
GlastCppPolicy_tag=$(tag)
GLASTCPPPOLICYROOT=/home/lucas/Glast/GlastRelease-v9r9p1/GlastPolicy/GlastCppPolicy/v1r6
GlastCppPolicy_root=/home/lucas/Glast/GlastRelease-v9r9p1/GlastPolicy/GlastCppPolicy/v1r6
GLASTCPPPOLICYVERSION=v1r6
GlastCppPolicy_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
GlastCppPolicy_offset=GlastPolicy
GlastCppPolicy_project=Project1
BINDIR=rh9_gcc32
cppoptions=$(cppdebugflags_s)
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
linkdebug=-g 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC  -ldl 
libraryshr_linkopts=-fPIC -ldl 
astro_tag=$(tag)
ASTROROOT=/home/lucas/Glast/GlastRelease-v9r9p1/astro/v1r18p1
astro_root=/home/lucas/Glast/GlastRelease-v9r9p1/astro/v1r18p1
ASTROVERSION=v1r18p1
astro_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
astro_project=Project1
facilities_tag=$(tag)
FACILITIESROOT=/home/lucas/Glast/GlastRelease-v9r9p1/facilities/v2r12p4
facilities_root=/home/lucas/Glast/GlastRelease-v9r9p1/facilities/v2r12p4
FACILITIESVERSION=v2r12p4
facilities_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
facilities_project=Project1
facilities_linkopts=-L${facilities_cmtpath}/lib -lfacilities 
cfitsio_tag=$(tag)
CFITSIOROOT=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/cfitsio/v1r2470p5
cfitsio_root=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/cfitsio/v1r2470p5
CFITSIOVERSION=v1r2470p5
cfitsio_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
cfitsio_offset=IExternal
cfitsio_project=Project1
cfitsio_native_version=v2470
cfitsio_DIR=${GLAST_EXT}/cfitsio/$(cfitsio_native_version)
cfitsio_libs=-L${cfitsio_DIR}/lib -lcfitsio 
cfitsio_linkopts=$(cfitsio_libs) 
LD_LIBRARY_PATH=/home/lucas/Glast/ScienceTools-v7r6p1/InstallArea/rh9_gcc32/lib:/home/lucas/GlastExternals/cppunit/1.10.2/lib:/home/lucas/GlastExternals/ROOT/v5.10.00/root/bin:/home/lucas/GlastExternals/ROOT/v5.10.00/root/lib:/home/lucas/GlastExternals/CLHEP/1.9.2.2/lib:/home/lucas/headas-6.1.2/i686-pc-linux-gnu-libc2.2.4/lib:/usr/X11R6/lib:/home/lucas/GlastExternals/cfitsio/v2470/lib:/home/lucas/Glast/ScienceTools-v7r6p1/lib/
CLHEP_tag=$(tag)
CLHEPROOT=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/CLHEP/v3r0
CLHEP_root=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/CLHEP/v3r0
CLHEPVERSION=v3r0
CLHEP_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
CLHEP_offset=IExternal
CLHEP_project=Project1
CLHEP_native_version=1.9.2.2
CLHEP_DIR=$(GLAST_EXT)/CLHEP
CLHEPBASE=${CLHEP_DIR}/$(CLHEP_native_version)
CLHEP_linkopts=-L$(CLHEPBASE)/lib -lCLHEP
extFiles_tag=$(tag)
EXTFILESROOT=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/extFiles/v0r5
extFiles_root=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/extFiles/v0r5
EXTFILESVERSION=v0r5
extFiles_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
extFiles_offset=IExternal
extFiles_project=Project1
extFiles_DIR=${GLAST_EXT}/extFiles
extFiles_native_version=v0r5
extFiles_PATH=${extFiles_DIR}/$(extFiles_native_version)
EXTFILESSYS=/home/lucas/GlastExternals/extFiles/v0r5
tip_tag=$(tag)
TIPROOT=/home/lucas/Glast/GlastRelease-v9r9p1/tip/v2r10
tip_root=/home/lucas/Glast/GlastRelease-v9r9p1/tip/v2r10
TIPVERSION=v2r10
tip_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
tip_project=Project1
STpolicy_tag=$(tag)
STPOLICYROOT=/home/lucas/Glast/GlastRelease-v9r9p1/STpolicy/v1r1
STpolicy_root=/home/lucas/Glast/GlastRelease-v9r9p1/STpolicy/v1r1
STPOLICYVERSION=v1r1
STpolicy_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
STpolicy_project=Project1
TMP=/tmp
ROOT_tag=$(tag)
ROOTROOT=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/ROOT/v5r10
ROOT_root=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/ROOT/v5r10
ROOTVERSION=v5r10
ROOT_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
ROOT_offset=IExternal
ROOT_project=Project1
ROOT_DIR=${GLAST_EXT}/ROOT
ROOT_native_version=v5.10.00
ROOT_PATH=${ROOT_DIR}/$(ROOT_native_version)/root
ROOTSYS=/home/lucas/GlastExternals/ROOT/v5.10.00/root
dict=../dict/
rootcint=rootcint
ROOT_libs=-L$(ROOT_PATH)/lib -lCore -lCint -lTree -lMatrix -lPhysics -lpthread -lm -ldl -rdynamic -lTreePlayer -lProof -lGX11 -lHist -lGraf -lGraf3d -lGpad -lThread -lHistPainter
ROOT_GUI_libs=-L$(ROOT_PATH)/lib -lHist -lGraf -lGraf3d -lGpad -lRint -lPostscript -lTreePlayer 
ROOT_linkopts=$(ROOT_libs) $(ROOT_GUI_libs)
ROOT_cppflagsEx=$(ppcmd) "$(ROOT_PATH)/include" -DUSE_ROOT
ROOT_cppflags=-fpermissive
DYLD_LIBRARY_PATH=/home/lucas/GlastExternals/ROOT/v5.10.00/root/lib:/home/lucas/GlastExternals/ROOT/v5.10.00/root/lib:
tip_linkopts=-lHist -L${tip_cmtpath}/lib -ltip 
tipDir=${TIPROOT}/${BINDIR}
tip_stamps=${TIPROOT}/${BINDIR}/tip.stamp 
astro_linkopts=-L${astro_cmtpath}/lib -lastro 
astro_stamps=${ASTROROOT}/${BINDIR}/astro.stamp 
st_facilities_tag=$(tag)
ST_FACILITIESROOT=/home/lucas/Glast/ScienceTools-v7r6p1/st_facilities/v0r7p3
st_facilities_root=/home/lucas/Glast/ScienceTools-v7r6p1/st_facilities/v0r7p3
ST_FACILITIESVERSION=v0r7p3
st_facilities_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
st_facilities_project=Project2
f2c_tag=$(tag)
F2CROOT=/home/lucas/Glast/GlastRelease-v9r9p1/f2c/v2r2
f2c_root=/home/lucas/Glast/GlastRelease-v9r9p1/f2c/v2r2
F2CVERSION=v2r2
f2c_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
f2c_project=Project1
f2c_linkopts= -lg2c 
cppunit_tag=$(tag)
CPPUNITROOT=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/cppunit/v2r0
cppunit_root=/home/lucas/Glast/GlastRelease-v9r9p1/IExternal/cppunit/v2r0
CPPUNITVERSION=v2r0
cppunit_cmtpath=/home/lucas/Glast/GlastRelease-v9r9p1
cppunit_offset=IExternal
cppunit_project=Project1
cppunit_native_version=1.10.2
cppunit_DIR=${GLAST_EXT}/cppunit/$(cppunit_native_version)
cppunit_linkopts=-L ${cppunit_DIR}/lib/ -lcppunit -ldl 
st_facilities_linkopts=-L${st_facilities_cmtpath}/lib -lst_facilities 
st_facilities_stamps=${ST_FACILITIESROOT}/${BINDIR}/st_facilities.stamp 
source=*.cxx
STTEST=sttest
irfInterface_linkopts=-L${irfInterface_cmtpath}/lib -lirfInterface -L${irfInterface_cmtpath}/lib -lirfInterface 
irfInterface_stamps=${IRFINTERFACEROOT}/${BINDIR}/irfInterface.stamp 
irfInterface_shlibflags=$(libraryshr_linkopts)
irfUtil_tag=$(tag)
IRFUTILROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/irfUtil/v0r4
irfUtil_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/irfUtil/v0r4
IRFUTILVERSION=v0r4
irfUtil_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
irfUtil_offset=irfs
irfUtil_project=Project2
irfUtilDir=${IRFUTILROOT}/${BINDIR}
irfUtil_linkopts=-L${irfUtil_cmtpath}/lib -lirfUtil 
irfUtil_stamps=${IRFUTILROOT}/${BINDIR}/irfUtil.stamp 
irfLoader_tag=$(tag)
IRFLOADERROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/irfLoader/v0r6p3
irfLoader_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/irfLoader/v0r6p3
IRFLOADERVERSION=v0r6p3
irfLoader_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
irfLoader_offset=irfs
irfLoader_project=Project2
dc1Response_tag=$(tag)
DC1RESPONSEROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/dc1Response/v1
dc1Response_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/dc1Response/v1
DC1RESPONSEVERSION=v1
dc1Response_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
dc1Response_offset=irfs
dc1Response_project=Project2
caldb_tag=$(tag)
CALDBROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/caldb/v0r1p1
caldb_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/caldb/v0r1p1
CALDBVERSION=v0r1p1
caldb_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
caldb_offset=irfs
caldb_project=Project2
CALDB=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/caldb/v0r1p1/CALDB
CALDBCONFIG=${CALDB}/software/tools/caldb.config
CALDBALIAS=${CALDB}/software/tools/alias_caldb.fits
dc1Response_linkopts=-L${dc1Response_cmtpath}/lib -ldc1Response -L${dc1Response_cmtpath}/lib -ldc1Response 
dc1Response_stamps=${DC1RESPONSEROOT}/${BINDIR}/dc1Response.stamp 
dc1Response_shlibflags=$(libraryshr_linkopts)
dc1aResponse_tag=$(tag)
DC1ARESPONSEROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/dc1aResponse/v1
dc1aResponse_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/dc1aResponse/v1
DC1ARESPONSEVERSION=v1
dc1aResponse_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
dc1aResponse_offset=irfs
dc1aResponse_project=Project2
dc1aResponse_linkopts=-L${dc1aResponse_cmtpath}/lib -ldc1aResponse 
dc1aResponse_stamps=${DC1ARESPONSEROOT}/${BINDIR}/dc1aResponse.stamp 
dc2Response_tag=$(tag)
DC2RESPONSEROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/dc2Response/v2
dc2Response_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/dc2Response/v2
DC2RESPONSEVERSION=v2
dc2Response_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
dc2Response_offset=irfs
dc2Response_project=Project2
dc2Response_linkopts=-L${dc2Response_cmtpath}/lib -ldc2Response 
dc2Response_stamps=${DC2RESPONSEROOT}/${BINDIR}/dc2Response.stamp 
g25Response_tag=$(tag)
G25RESPONSEROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/g25Response/v1
g25Response_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/g25Response/v1
G25RESPONSEVERSION=v1
g25Response_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
g25Response_offset=irfs
g25Response_project=Project2
g25Response_linkopts=-L${g25Response_cmtpath}/lib -lg25Response -L${g25Response_cmtpath}/lib -lg25Response 
g25Response_stamps=${G25RESPONSEROOT}/${BINDIR}/g25Response.stamp 
g25Response_shlibflags=$(libraryshr_linkopts)
testResponse_tag=$(tag)
TESTRESPONSEROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/testResponse/v1
testResponse_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/testResponse/v1
TESTRESPONSEVERSION=v1
testResponse_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
testResponse_offset=irfs
testResponse_project=Project2
testResponse_linkopts=-L${testResponse_cmtpath}/lib -ltestResponse 
testResponse_stamps=${TESTRESPONSEROOT}/${BINDIR}/testResponse.stamp 
handoff_response_tag=$(tag)
HANDOFF_RESPONSEROOT=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/handoff_response/v1r2p2
handoff_response_root=/home/lucas/Glast/ScienceTools-v7r6p1/irfs/handoff_response/v1r2p2
HANDOFF_RESPONSEVERSION=v1r2p2
handoff_response_cmtpath=/home/lucas/Glast/ScienceTools-v7r6p1
handoff_response_offset=irfs
handoff_response_project=Project2
handoff_response_linkopts=-L${handoff_response_cmtpath}/lib -lhandoff_response 
handoff_response_stamps=${HANDOFF_RESPONSEROOT}/${BINDIR}/handoff_response.stamp 
handoff_response_cppflags=-I ../src -g  
irfLoader_linkopts=-L${irfLoader_cmtpath}/lib -lirfLoader -L${irfLoader_cmtpath}/lib -lirfLoader 
irfLoader_stamps=${IRFLOADERROOT}/${BINDIR}/irfLoader.stamp 
irfLoader_shlibflags=$(libraryshr_linkopts)
GlastPatternPolicyDir=${GLASTPATTERNPOLICYROOT}/${BINDIR}
GlastPolicyDir=${GLASTPOLICYROOT}/${BINDIR}
facilitiesDir=${FACILITIESROOT}/${BINDIR}
STpolicyDir=${STPOLICYROOT}/${BINDIR}
astroDir=${ASTROROOT}/${BINDIR}
f2cDir=${F2CROOT}/${BINDIR}
st_facilitiesDir=${ST_FACILITIESROOT}/${BINDIR}
irfInterfaceDir=${IRFINTERFACEROOT}/${BINDIR}
dc1ResponseDir=${DC1RESPONSEROOT}/${BINDIR}
dc1aResponseDir=${DC1ARESPONSEROOT}/${BINDIR}
dc2ResponseDir=${DC2RESPONSEROOT}/${BINDIR}
g25ResponseDir=${G25RESPONSEROOT}/${BINDIR}
testResponseDir=${TESTRESPONSEROOT}/${BINDIR}
handoff_responseDir=${HANDOFF_RESPONSEROOT}/${BINDIR}
irfLoaderDir=${IRFLOADERROOT}/${BINDIR}
irfsDir=${IRFSROOT}/${BINDIR}
CMTINSTALLAREA=/home/lucas/Glast/ScienceTools-v7r6p1/InstallArea
tag=rh9_gcc32
package=irfs
version=v0r9p2
PACKAGE_ROOT=$(IRFSROOT)
srcdir=../src
bin=../$(irfs_tag)/
javabin=../classes/
mgrdir=cmt
project=Project2
use_requirements=requirements $(CMTROOT)/mgr/requirements $(IRFLOADERROOT)/cmt/requirements $(DC1RESPONSEROOT)/cmt/requirements $(DC1ARESPONSEROOT)/cmt/requirements $(DC2RESPONSEROOT)/cmt/requirements $(G25RESPONSEROOT)/cmt/requirements $(TESTRESPONSEROOT)/cmt/requirements $(HANDOFF_RESPONSEROOT)/cmt/requirements $(IRFINTERFACEROOT)/cmt/requirements $(ST_FACILITIESROOT)/cmt/requirements $(IRFUTILROOT)/cmt/requirements $(ASTROROOT)/cmt/requirements $(FACILITIESROOT)/cmt/requirements $(TIPROOT)/cmt/requirements $(STPOLICYROOT)/cmt/requirements $(F2CROOT)/cmt/requirements $(GLASTPOLICYROOT)/cmt/requirements $(GLASTPATTERNPOLICYROOT)/cmt/requirements $(GLASTCPPPOLICYROOT)/cmt/requirements $(CFITSIOROOT)/cmt/requirements $(CLHEPROOT)/cmt/requirements $(EXTFILESROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(CPPUNITROOT)/cmt/requirements $(CALDBROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(IRFLOADERROOT)" $(ppcmd)"$(DC1RESPONSEROOT)" $(ppcmd)"$(DC1ARESPONSEROOT)" $(ppcmd)"$(DC2RESPONSEROOT)" $(ppcmd)"$(G25RESPONSEROOT)" $(ppcmd)"$(TESTRESPONSEROOT)" $(ppcmd)"$(HANDOFF_RESPONSEROOT)" $(ppcmd)"$(IRFINTERFACEROOT)" $(ppcmd)"$(ST_FACILITIESROOT)" $(ppcmd)"$(IRFUTILROOT)" $(ppcmd)"$(ASTROROOT)" $(ppcmd)"$(FACILITIESROOT)" $(ppcmd)"$(TIPROOT)" $(ppcmd)"$(F2CROOT)" $(ppcmd)"${cfitsio_DIR}/include" $(ppcmd)"$(CLHEPBASE)/include" $(ppcmd)"$(ROOT_PATH)/include" $(ppcmd)"${cppunit_DIR}/include" $(ppcmd)"$(caldb_root)/src" 
use_fincludes= $(use_includes)
use_stamps= $(irfs_stamps)  $(irfLoader_stamps)  $(dc1Response_stamps)  $(dc1aResponse_stamps)  $(dc2Response_stamps)  $(g25Response_stamps)  $(testResponse_stamps)  $(handoff_response_stamps)  $(irfInterface_stamps)  $(st_facilities_stamps)  $(irfUtil_stamps)  $(astro_stamps)  $(facilities_stamps)  $(tip_stamps)  $(STpolicy_stamps)  $(f2c_stamps)  $(GlastPolicy_stamps)  $(GlastPatternPolicy_stamps)  $(GlastCppPolicy_stamps)  $(cfitsio_stamps)  $(CLHEP_stamps)  $(extFiles_stamps)  $(ROOT_stamps)  $(cppunit_stamps)  $(caldb_stamps) 
use_cflags=  $(irfs_cflags)  $(irfLoader_cflags)  $(dc1Response_cflags)  $(dc1aResponse_cflags)  $(dc2Response_cflags)  $(g25Response_cflags)  $(testResponse_cflags)  $(handoff_response_cflags)  $(irfInterface_cflags)  $(st_facilities_cflags)  $(irfUtil_cflags)  $(astro_cflags)  $(facilities_cflags)  $(tip_cflags)  $(STpolicy_cflags)  $(f2c_cflags)  $(GlastPolicy_cflags)  $(cfitsio_cflags)  $(CLHEP_cflags)  $(extFiles_cflags)  $(ROOT_cflags)  $(cppunit_cflags)  $(caldb_cflags) 
use_pp_cflags=  $(irfs_pp_cflags)  $(irfLoader_pp_cflags)  $(dc1Response_pp_cflags)  $(dc1aResponse_pp_cflags)  $(dc2Response_pp_cflags)  $(g25Response_pp_cflags)  $(testResponse_pp_cflags)  $(handoff_response_pp_cflags)  $(irfInterface_pp_cflags)  $(st_facilities_pp_cflags)  $(irfUtil_pp_cflags)  $(astro_pp_cflags)  $(facilities_pp_cflags)  $(tip_pp_cflags)  $(STpolicy_pp_cflags)  $(f2c_pp_cflags)  $(GlastPolicy_pp_cflags)  $(cfitsio_pp_cflags)  $(CLHEP_pp_cflags)  $(extFiles_pp_cflags)  $(ROOT_pp_cflags)  $(cppunit_pp_cflags)  $(caldb_pp_cflags) 
use_cppflags=  $(irfs_cppflags)  $(irfLoader_cppflags)  $(dc1Response_cppflags)  $(dc1aResponse_cppflags)  $(dc2Response_cppflags)  $(g25Response_cppflags)  $(testResponse_cppflags)  $(handoff_response_cppflags)  $(irfInterface_cppflags)  $(st_facilities_cppflags)  $(irfUtil_cppflags)  $(astro_cppflags)  $(facilities_cppflags)  $(tip_cppflags)  $(STpolicy_cppflags)  $(f2c_cppflags)  $(GlastPolicy_cppflags)  $(cfitsio_cppflags)  $(CLHEP_cppflags)  $(extFiles_cppflags)  $(ROOT_cppflags)  $(cppunit_cppflags)  $(caldb_cppflags) 
use_pp_cppflags=  $(irfs_pp_cppflags)  $(irfLoader_pp_cppflags)  $(dc1Response_pp_cppflags)  $(dc1aResponse_pp_cppflags)  $(dc2Response_pp_cppflags)  $(g25Response_pp_cppflags)  $(testResponse_pp_cppflags)  $(handoff_response_pp_cppflags)  $(irfInterface_pp_cppflags)  $(st_facilities_pp_cppflags)  $(irfUtil_pp_cppflags)  $(astro_pp_cppflags)  $(facilities_pp_cppflags)  $(tip_pp_cppflags)  $(STpolicy_pp_cppflags)  $(f2c_pp_cppflags)  $(GlastPolicy_pp_cppflags)  $(cfitsio_pp_cppflags)  $(CLHEP_pp_cppflags)  $(extFiles_pp_cppflags)  $(ROOT_pp_cppflags)  $(cppunit_pp_cppflags)  $(caldb_pp_cppflags) 
use_fflags=  $(irfs_fflags)  $(irfLoader_fflags)  $(dc1Response_fflags)  $(dc1aResponse_fflags)  $(dc2Response_fflags)  $(g25Response_fflags)  $(testResponse_fflags)  $(handoff_response_fflags)  $(irfInterface_fflags)  $(st_facilities_fflags)  $(irfUtil_fflags)  $(astro_fflags)  $(facilities_fflags)  $(tip_fflags)  $(STpolicy_fflags)  $(f2c_fflags)  $(GlastPolicy_fflags)  $(cfitsio_fflags)  $(CLHEP_fflags)  $(extFiles_fflags)  $(ROOT_fflags)  $(cppunit_fflags)  $(caldb_fflags) 
use_pp_fflags=  $(irfs_pp_fflags)  $(irfLoader_pp_fflags)  $(dc1Response_pp_fflags)  $(dc1aResponse_pp_fflags)  $(dc2Response_pp_fflags)  $(g25Response_pp_fflags)  $(testResponse_pp_fflags)  $(handoff_response_pp_fflags)  $(irfInterface_pp_fflags)  $(st_facilities_pp_fflags)  $(irfUtil_pp_fflags)  $(astro_pp_fflags)  $(facilities_pp_fflags)  $(tip_pp_fflags)  $(STpolicy_pp_fflags)  $(f2c_pp_fflags)  $(GlastPolicy_pp_fflags)  $(cfitsio_pp_fflags)  $(CLHEP_pp_fflags)  $(extFiles_pp_fflags)  $(ROOT_pp_fflags)  $(cppunit_pp_fflags)  $(caldb_pp_fflags) 
use_linkopts= $(cmt_installarea_linkopts)   $(irfs_linkopts)  $(irfLoader_linkopts)  $(dc1Response_linkopts)  $(dc1aResponse_linkopts)  $(dc2Response_linkopts)  $(g25Response_linkopts)  $(testResponse_linkopts)  $(handoff_response_linkopts)  $(irfInterface_linkopts)  $(st_facilities_linkopts)  $(irfUtil_linkopts)  $(astro_linkopts)  $(facilities_linkopts)  $(tip_linkopts)  $(STpolicy_linkopts)  $(f2c_linkopts)  $(GlastPolicy_linkopts)  $(cfitsio_linkopts)  $(CLHEP_linkopts)  $(extFiles_linkopts)  $(ROOT_linkopts)  $(cppunit_linkopts)  $(caldb_linkopts) 
use_libraries= $(irfLoader_libraries)  $(dc1Response_libraries)  $(dc1aResponse_libraries)  $(dc2Response_libraries)  $(g25Response_libraries)  $(testResponse_libraries)  $(handoff_response_libraries)  $(irfInterface_libraries)  $(st_facilities_libraries)  $(irfUtil_libraries)  $(astro_libraries)  $(facilities_libraries)  $(tip_libraries)  $(STpolicy_libraries)  $(f2c_libraries)  $(GlastPolicy_libraries)  $(GlastPatternPolicy_libraries)  $(GlastCppPolicy_libraries)  $(cfitsio_libraries)  $(CLHEP_libraries)  $(extFiles_libraries)  $(ROOT_libraries)  $(cppunit_libraries)  $(caldb_libraries) 
includes= $(use_includes)
fincludes= $(includes)
constituents= 
all_constituents= $(constituents)
constituentsclean= 
all_constituentsclean= $(constituentsclean)
cmt_installarea_paths=$(cmt_installarea_prefix)/$(tag)/bin $(cmt_installarea_prefix)/$(tag)/lib $(cmt_installarea_prefix)/share/lib $(cmt_installarea_prefix)/share/bin
Project2_installarea_prefix=$(cmt_installarea_prefix)
Project2_installarea_prefix_remove=$(Project2_installarea_prefix)
cmt_installarea_linkopts= -L/home/lucas/Glast/ScienceTools-v7r6p1/$(Project2_installarea_prefix)/$(tag)/lib 
